[phases.setup]
nixPkgs = ["git", "git-lfs"]
cmds = ["git lfs install", "git lfs pull"]

[phases.install]
cmds = [
  "chmod +x railway_prebuild.sh",
  "./railway_prebuild.sh",
  "pip install -r requirements.txt"
]